version: 2
jobs:
  build:
      docker:
        - image: circleci/golang:1.12
      working_directory: ~/Ambitine
      steps:
        - checkout
        - run: go get -v -u
        #- run: go run main.go

  deploy:
    machine:
      enabled: true
    working_directory: ~/repo
    steps:
      - checkout
      - add_ssh_keys:
            fingerprints:
              - "5c:04:27:28:22:31:b0:bc:62:5b:24:56:1e:16:5b:c0"
      - run:
          name: Deploy Over SSH
          command: |
            ssh root@104.248.254.28 "cd Ambitine_backend; git pull"
            ssh root@104.248.254.28 "cd Ambitine_backend; sudo docker kill ambitine_backend_ambitine_1"
            ssh root@104.248.254.28 'cd Ambitine_backend; sudo docker rm ambitine_backend_ambitine_1'
            ssh root@104.248.254.28 "cd Ambitine_backend; sudo docker-compose up -d"


# davai da dad
#            ssh ntn@35.228.75.3 git clone https://github.com/Pickausernaame/Ambitine_backend.git


workflows:
  version: 2
  workflow:
    jobs:
      - deploy
