version: 2
jobs:
  build:
      docker:
        - image: circleci/golang:1.12
      working_directory: ~/Ambitine
      steps:
        - checkout
        - run: go get -v -u
        #- run: go run main.go

  deploy:
    machine:
      enabled: true
    working_directory: ~/repo
    steps:
      - checkout
      - add_ssh_keys:
            fingerprints:
              - "a3:24:d9:10:de:84:19:a3:f6:9a:c7:dd:ae:59:08:97"
      - run:
          name: Deploy Over SSH
          command: |
            ssh root@104.248.254.28 "cd Ambitine_backend; git pull"
            ssh root@104.248.254.28 "cd Ambitine_backend; sudo docker-compose up --no-deps --build -d ambitine"
            ssh root@104.248.254.28 'cd Ambitine_backend; sudo docker rmi $(sudo docker images -f "dangling=true" -q)'



#            ssh ntn@35.228.75.3 git clone https://github.com/Pickausernaame/Ambitine_backend.git


workflows:
  version: 2
  workflow:
    jobs:
      - deploy
