version: 2
jobs:
  build:
      docker:
        - image: circleci/golang:1.12
      working_directory: ~/Ambitine
      steps:
        - checkout
        - run: go get -v -u
        #- run: go run main.go

  deploy:
    machine:
      enabled: true
    working_directory: ~/repo
    steps:
      - checkout
      - add_ssh_keys:
            fingerprints:
              - "43:57:31:94:df:f1:77:18:ed:2b:73:16:41:b8:ec:7c"
      - run:
          name: fix host authenticity for production server
          command: ssh-keyscan 35.228.75.3 >> ~/.ssh/known_hosts
      - run:
          name: Deploy Over SSH
          command: |
            ssh 35.228.75.3 rm build
            ssh 35.228.75.3 mkdir build
            ssh 35.228.75.3 cd build
            ssh 35.228.75.3 git clone https://github.com/Pickausernaame/Ambitine_backend.git
            ssh 35.228.75.3 cd Ambitine_backend
            ssh 35.228.75.3 sudo docker_clean.sh
            ssh 35.228.75.3 sudo docker-compose up

workflows:
  version: 2
  workflow:
    jobs:
      - deploy